name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: "docker-vnc:latest"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          if [ -f docker-compose.yml ]; then
            docker-compose --file docker-compose.yml build
            docker-compose --file docker-compose.yml up
            docker-compose --file docker-compose.yml down
          else
            docker build . --file Dockerfile --tag docker-vnc:$(date +%s)
          fi
